server:
  port: 8080

spring:
  application:
    name: xkcd-data-hub-lite

management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      probes.enabled: true
      show-details: always
  health:
    livenessstate.enabled: true
    readinessstate.enabled: true

xkcd:
  base-url: https://xkcd.com
  cronjob:
    schedule: "0 0 */12 * * *"
  fetch:
    on-startup: true
    producers: 10
    consumers: 15
    max-queue-size: 50

