openapi: 3.0.3
info:
  title: XKCD Data Hub API
  description: |
    The XKCD Data Hub API provides an entry point for fetching and streaming
    XKCD comic data. Users can retrieve information about specific comics,
    search by keywords, or get the latest comics.
  contact:
    name: Yonatan Karp-Rudin
    url: http://yonatankarp.com
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development environment

tags:
  - name: GetByComicId
    description: Retrieve XKCD comic by ID
  - name: Search
    description: Search XKCD comics
  - name: GetLatestComics
    description: Retrieve the latest XKCD comic
  - name: XkcdDataHubV1
    description: Endpoints for XKCD Data Hub version 1

paths:
  /xkcd/webcomics/{comicId}:
    get:
      operationId: getXkcdComicById
      summary: Retrieve XKCD comic by ID
      description: |
        This endpoint retrieves the XKCD comic associated with the specified ID.
      tags:
        - GetByComicId
        - XkcdDataHubV1
      parameters:
        - name: comicId
          in: path
          required: true
          description: The ID of the XKCD comic to retrieve
          schema:
            type: integer
            example: 123
      responses:
        "200":
          description: A successful response containing information about the XKCD comic.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ComicResponse"
        "400":
          description: The request was invalid.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
        "404":
          description: The requested resource was not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
        "500":
          description: An unexpected server error occurred.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"

  /xkcd/webcomics/search:
    get:
      operationId: search_as_you_type
      summary: Search XKCD comics by keyword
      description: |
        This endpoint searches XKCD comics based on the provided keyword.
      tags:
        - Search
        - XkcdDataHubV1
      parameters:
        - name: keyword
          in: query
          required: true
          description: The keyword to search for in XKCD comics
          schema:
            type: string
            example: "science"
      responses:
        "200":
          description: A successful response containing a list of XKCD comics matching the keyword.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ComicResponse"
        "400":
          description: The request was invalid.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
        "500":
          description: An unexpected server error occurred.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"

  /xkcd/webcomics/latest:
    get:
      operationId: get_latest_xkcd_comics
      summary: Retrieve the latest XKCD comics
      description: |
        This endpoint retrieves the latest XKCD comic.
      tags:
        - GetLatestComics
        - XkcdDataHubV1
      responses:
        "200":
          description: A successful response containing information about the latest XKCD comic.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ComicResponse"
        "500":
          description: An unexpected server error occurred.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"

components:
  schemas:
    ComicResponse:
      type: object
      required:
        - id
        - year
        - month
        - day
        - title
        - safe_title
        - alternative_text
        - image_url
        - created_at
      properties:
        id:
          type: integer
          description: The ID of the XKCD comic
          example: 472
        year:
          type: integer
          description: The year the XKCD comic was published
          example: 2008
        month:
          type: integer
          description: The month the XKCD comic was published
          example: 9
        day:
          type: integer
          description: The day the XKCD comic was published
          example: 5
        title:
          type: string
          description: The title of the XKCD comic
          example: |
            <span style="color: #0000ED">House</span> of Pancakes
        safe_title:
          type: string
          description: The safe title of the XKCD comic
          example: "House of Pancakes"
        transcript:
          type: string
          description: The transcript of the XKCD comic
          example: |
            {{All instances of the word "House" are in blue.}}
            Every day a new city, a new IHOP. And yet every night the dreams get worse. I ply the highways, a nervous eye on the rear-view mirror, the back seat piled with stolen menus. Their doors are opened 24 hours, but forever closed to my soul. This is what my life has become. This is my hell.
            {{sidenote left: International}}
            House of Pancakes
            {{scribbled-out sidenote right: BLOGSPOT}}
            Strawberry Banana Pancakes
            Four pancakes filled with sliced fresh banana and crowned with cool strawberry topping, more [17] bananas and [23] whipped topping.
            [17] Driven by a nameless fear, a whisper in the dark behind me, I flee ahead of I know not what. Whenver I turn, there's nobody behind me.  And yet someone is clearly stealing the ketchup. WHY?
            [[The footnote is covered in fingerprints.]]
            [23] My life is feeding,
            fleeing,
            fighting,
            and
            forgetting.
            [[The above note is sandwiched in sideways in between the Stuffed French Toast and Ham and Egg Melt.]]
            Rooty Jr.
            A kids only [19] version of our house signature Rooty Tooty. One scrambled egg, one strip of bacon, one pork sausage link and one fruit-topped buttermilk pancake.
            [19] The decision not to hyphenate "kids only" is likely connected to the omission of the serial comma. I wonder if the author is British. I wonder if he sleeps at night.
            [[The following passages are have a red substance underneath them, probably ketchup.]]
            Rise 'N Shine
            Two eggs, toast and hash browns served with your choice [21] of two strips of bacon or two pork sausage links.
            [21] {{illegible}} rent a storage unit. Sleep there. Fill it with pancakes. Leave.
            Stuffed French Toast
            Cinnamon raisin French [18] toast stuffed with sweet cream cheese filling, topped with cool strawberry or your choice of fruit compote and whipped topping.
            [18] Nightmares again. I wake up covered in sweat, and what appears to be a thin sheen of maple syrup
            {{Handwritten, underlined}} WHO IS MOHAWK GIRL?
            [[Slanted 90 degrees left]]
            Ham & Egg Melt
            Grilled sourdough bread stuffed with ham, scrambled eggs, Swiss and American cheeses. [20]
            [[At normal orientation]]
            [20] Ordered this in at an IHOP in Rochester, New York. There was blood on the floor. Some of it was mine.
            [[Comic strip]]
            Enough with your pancakes.
            Enough with your GOD DAMN pancakes.
            The Big Steak Omlette
            Tender strips of steak, hash browns, {{redacted}} tomatoes and Cheddar cheese. Served [22] with house salsa.
            [22] Woke up in Las Vegas.  They're closing the Star Trek Experience today.  The IHOP up the strip had pancake platters named after various states.
            None of them sounded like home.
            {{Alt text: Fuck it, I'm just going to Waffle House.}}
            {{External link: http:
            www.amazon.com
            House-Leaves-Mark-Z-Danielewski
            dp
            0375703764}}
        alternative_text:
          type: string
          description: The alternative text of the XKCD comic
          example: "Fuck it.  I'm just going to Waffle House."
        image_url:
          type: string
          description: The URL of the XKCD comic image
          example: "https://imgs.xkcd.com/comics/house_of_pancakes.png"
        news:
          type: string
          description: News related to the XKCD comic
          example: |
            (Today's comic is a parody of <a href="https://www.amazon.com/House-Leaves-Mark-Z-Danielewski/dp/0375703764">House of Leaves</a>.)
        link:
          type: string
          description: Additional link related to the XKCD comic
          example: "https://www.amazon.com/House-Leaves-Mark-Z-Danielewski/dp/0375703764"
        created_at:
          type: string
          description: The creation date of the XKCD comic
          format: date-time
          example: "2024-06-30T14:48:00.000Z"

    ApiError:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Machine-readable error code
          example: "NotFound"
        message:
          type: string
          description: A human-readable error message
          example: "The requested resource was not found"
        details:
          type: string
          description: Additional details about the error
          example: "No comic found with ID 123"
